require_relative('../models/day')
require_relative('../models/restaurant')
require_relative('../models/burger')
require_relative('../models/deal')
require_relative('../models/burger_deal')

BurgerDeal.delete_all()
Deal.delete_all()
Burger.delete_all()
Restaurant.delete_all()
Day.delete_all()

monday = Day.new({ "name" => "Monday"})
tuesady = Day.new({ "name" => "Tuesday"})
wednesday = Day.new({ "name" => "Wednesday"})
thursday = Day.new({ "name" => "Thursday"})
friday = Day.new({ "name" => "Friday"})
saturday = Day.new({ "name" => "Saturday"})
sunday = Day.new({ "name" => "Sunday"})


monday.save()
tuesady.save()
wednesday.save()
thursday.save()
friday.save()
saturday .save()
sunday.save()